In [1]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.



In [2]:
import numpy as np

In [5]:
arr = np.array(
    [2, 4, 6, 8]
)

In [6]:
print(arr)

[2 4 6 8]


In [7]:
print(type(arr))

<class 'numpy.ndarray'>


In [8]:
tuple = np.array((1,3,5,7,9))

In [9]:
print(tuple)

[1 3 5 7 9]


In [10]:
print(type(tuple))

<class 'numpy.ndarray'>


### 0-D arrays

In [21]:
print(
    np.array(43)
)

43


### 1-D arrays

In [19]:
print(
    np.array(
        [1,6,9,0]
    )
)

[1 6 9 0]


### 2-D arrays
note:: NumPy has a whole sub module dedicated towards matrix operations called `numpy.mat`

In [20]:
print(
    np.array(
        [
            [1,3,4],
            [7,1,3]
        ]
    )
)

[[1 3 4]
 [7 1 3]]


### 3-D arrays

In [23]:
print(
    np.array(
        [
            [
                [1,3,5],
                [2,4,6]
            ],
            [
                [-1,9,0],
                [-5,-7,-2]
            ]
        ]
    )
)

[[[ 1  3  5]
  [ 2  4  6]]

 [[-1  9  0]
  [-5 -7 -2]]]


#### check the number of dimensions

In [24]:
a = np.array(7) # 0 dimension
b = np.array([3,1,7])  # 1 dimension
c = np.array([[1,0,6], [8,7,4]])  # 2 dimension
d = np.array([[[4,0,-1],[6,-6,3]],[[-9,2,4],[5,1,8]]])  # 3 dimension

In [26]:
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


### Higher dimensional arrays

In [28]:
hd_array = np.array([6,9,1], ndmin=5)

print(hd_array.ndim)

5


### Array indexing

In [3]:
my_arr = np.array([3,1,8,2])

In [4]:
print(
    my_arr[0]
)

3


In [6]:
# adding two elements of the array
print(
    my_arr[1] + my_arr[2]
)

9


In [7]:
# 2-d array
trr = np.array([[2,6,9], [1,0,4]])

In [10]:
print(
    trr[0] # [2 6 9]
)

[2 6 9]


In [11]:
print(
    trr[0, 1] #6
)

6


In [13]:
print(
    trr[1, 1] # 0
)

0


In [17]:
# access 3-d arrays

three_arr = np.array(
    [
        [
            [-3, 5, 1],
            [7, 2, 6]
        ],
        [
            [4,-5,3],
            [-6,7,9]
        ]
    ]
)

In [20]:
print(
    three_arr[0, 1, 2]
)

6


In [22]:
sudoku = np.array(
    [
        [
            [
                [1,2,6],
                [4,3,8],
                [0,9,5]
            ],
            [
                [4,9,-6],
                [-1,2,7],
                [6,-5,-3]
            ],
            [
                [3,50,7],
                [5,9,80],
                [29,1,92]
            ]
        ],
        [
            [
                [99,19,41],
                [57,36,22],
                [30,15,12]
            ],
            [
                [30,41,45],
                [60,69,71],
                [76,82,66]
            ],
            [
                [35,50,55],
                [75,80,96],
                [36,35,18]
            ]
        ],
        [
            [
                [63,51,79],
                [77,49,81],
                [27,87,95]
            ],
            [
                [20,12,14],
                [22,28,67],
                [8,11,10]
            ],
            [
                [41,3,33],
                [5,54,52],
                [2,6,9]
            ]
        ]
    ]
)

In [23]:
print(
    sudoku[1,1,1,1]
)

69


In [24]:
print(
    sudoku[2,0,0,2] # 79
)

79


In [29]:
# negative indexing

narr = np.array(
    [
        [3,8,1,0,4,7],
        [7,1,5,9,2,6]
    ]
)

In [30]:
print(
    narr[1,-3]
)

9
