In [1]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.



In [3]:
import numpy as np

In [5]:
arr = np.array(
    [2, 4, 6, 8]
)

In [6]:
print(arr)

[2 4 6 8]


In [7]:
print(type(arr))

<class 'numpy.ndarray'>


In [8]:
tuple = np.array((1,3,5,7,9))

In [9]:
print(tuple)

[1 3 5 7 9]


In [10]:
print(type(tuple))

<class 'numpy.ndarray'>


### 0-D arrays

In [21]:
print(
    np.array(43)
)

43


### 1-D arrays

In [19]:
print(
    np.array(
        [1,6,9,0]
    )
)

[1 6 9 0]


### 2-D arrays
note:: NumPy has a whole sub module dedicated towards matrix operations called `numpy.mat`

In [20]:
print(
    np.array(
        [
            [1,3,4],
            [7,1,3]
        ]
    )
)

[[1 3 4]
 [7 1 3]]


### 3-D arrays

In [23]:
print(
    np.array(
        [
            [
                [1,3,5],
                [2,4,6]
            ],
            [
                [-1,9,0],
                [-5,-7,-2]
            ]
        ]
    )
)

[[[ 1  3  5]
  [ 2  4  6]]

 [[-1  9  0]
  [-5 -7 -2]]]


#### check the number of dimensions

In [24]:
a = np.array(7) # 0 dimension
b = np.array([3,1,7])  # 1 dimension
c = np.array([[1,0,6], [8,7,4]])  # 2 dimension
d = np.array([[[4,0,-1],[6,-6,3]],[[-9,2,4],[5,1,8]]])  # 3 dimension

In [26]:
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


### Higher dimensional arrays

In [28]:
hd_array = np.array([6,9,1], ndmin=5)

print(hd_array.ndim)

5
