In [48]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [49]:
import numpy as np

In [50]:
arr = np.array(
    [2, 4, 6, 8]
)

In [51]:
print(arr)

[2 4 6 8]


In [52]:
print(type(arr))

<class 'numpy.ndarray'>


In [53]:
tuple = np.array((1,3,5,7,9))

In [54]:
print(tuple)

[1 3 5 7 9]


In [55]:
print(type(tuple))

<class 'numpy.ndarray'>


### 0-D arrays

In [56]:
print(
    np.array(43)
)

43


### 1-D arrays

In [57]:
print(
    np.array(
        [1,6,9,0]
    )
)

[1 6 9 0]


### 2-D arrays
note:: NumPy has a whole sub module dedicated towards matrix operations called `numpy.mat`

In [58]:
print(
    np.array(
        [
            [1,3,4],
            [7,1,3]
        ]
    )
)

[[1 3 4]
 [7 1 3]]


### 3-D arrays

In [59]:
print(
    np.array(
        [
            [
                [1,3,5],
                [2,4,6]
            ],
            [
                [-1,9,0],
                [-5,-7,-2]
            ]
        ]
    )
)

[[[ 1  3  5]
  [ 2  4  6]]

 [[-1  9  0]
  [-5 -7 -2]]]


#### check the number of dimensions

In [60]:
a = np.array(7) # 0 dimension
b = np.array([3,1,7])  # 1 dimension
c = np.array([[1,0,6], [8,7,4]])  # 2 dimension
d = np.array([[[4,0,-1],[6,-6,3]],[[-9,2,4],[5,1,8]]])  # 3 dimension

In [61]:
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


### Higher dimensional arrays

In [62]:
hd_array = np.array([6,9,1], ndmin=5)

print(hd_array.ndim)

5


### Array indexing

In [63]:
my_arr = np.array([3,1,8,2])

In [64]:
print(
    my_arr[0]
)

3


In [65]:
# adding two elements of the array
print(
    my_arr[1] + my_arr[2]
)

9


In [66]:
# 2-d array
trr = np.array([[2,6,9], [1,0,4]])

In [67]:
print(
    trr[0] # [2 6 9]
)

[2 6 9]


In [68]:
print(
    trr[0, 1] #6
)

6


In [69]:
print(
    trr[1, 1] # 0
)

0


In [70]:
# access 3-d arrays

three_arr = np.array(
    [
        [
            [-3, 5, 1],
            [7, 2, 6]
        ],
        [
            [4,-5,3],
            [-6,7,9]
        ]
    ]
)

In [71]:
print(
    three_arr[0, 1, 2]
)

6


In [72]:
sudoku = np.array(
    [
        [
            [
                [1,2,6],
                [4,3,8],
                [0,9,5]
            ],
            [
                [4,9,-6],
                [-1,2,7],
                [6,-5,-3]
            ],
            [
                [3,50,7],
                [5,9,80],
                [29,1,92]
            ]
        ],
        [
            [
                [99,19,41],
                [57,36,22],
                [30,15,12]
            ],
            [
                [30,41,45],
                [60,69,71],
                [76,82,66]
            ],
            [
                [35,50,55],
                [75,80,96],
                [36,35,18]
            ]
        ],
        [
            [
                [63,51,79],
                [77,49,81],
                [27,87,95]
            ],
            [
                [20,12,14],
                [22,28,67],
                [8,11,10]
            ],
            [
                [41,3,33],
                [5,54,52],
                [2,6,9]
            ]
        ]
    ]
)

In [73]:
print(
    sudoku[1,1,1,1]
)

69


In [74]:
print(
    sudoku[2,0,0,2] # 79
)

79


In [75]:
# negative indexing

narr = np.array(
    [
        [3,8,1,0,4,7],
        [7,1,5,9,2,6]
    ]
)

In [76]:
print(
    narr[1,-3]
)

9


### Array Slicing

In [77]:
arr = np.array(
    [2,4,6,8,10,12]
)

print(arr[1:4]) # Note: The result includes the start index, but excludes the end index.
print(arr[:3])
print(arr[3:])

[4 6 8]
[2 4 6]
[ 8 10 12]


In [78]:
# negative slicing

brr = np.array(
    [2,1,3,6,9,11]
)

print(brr[-5:-2]) # Note: The result includes the start index, but excludes the end index.

[1 3 6]


In [79]:
# step
srr = np.array(
    [-5,1,3,5,7,9,11,13,17,42,91]
)

print(srr[2:9:1])
print(srr[2:9:2])
print(srr[::3])

[ 3  5  7  9 11 13 17]
[ 3  7 11 17]
[-5  5 11 42]


In [80]:
#######         Slicing 2-D arrays          #########

trr= np.array(
    [
        [1,2,3,4,5],
        [6,7,8,9,10]
    ]
)

print(trr[1, 1:4])

# from both elements
print(trr[0:2, 2])

# From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:
print(trr[0:2, 1:4])


[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


### Execise

In [81]:
# 1
'''
Insert the correct slicing syntax to print the following selection of the array:

Everything from (including) the second item to (not including) the fifth item.

arr = np.array([10, 15, 20, 25, 30, 35, 40])

print(arr[?])
'''
arr = np.array([10, 15, 20, 25, 30, 35, 40])
print(arr[1:4])

[15 20 25]


In [82]:
# 2
'''
Insert the correct slicing syntax to print the following selection of the array:

Everything from (including) the third item to (not including) the fifth item.

arr = np.array([10, 15, 20, 25, 30, 35, 40])

print(arr[?])
'''

arr = np.array([10, 15, 20, 25, 30, 35, 40])
print(arr[2:4])

[20 25]


In [83]:
# 3
'''
Insert the correct slicing syntax to print the following selection of the array:

Every other item from (including) the second item to (not including) the fifth item.

Tip: use the step syntax.

arr = np.array([10, 15, 20, 25, 30, 35, 40])

print(arr[?])
'''

arr = np.array([10, 15, 20, 25, 30, 35, 40])
print(arr[1:4:2])

[15 25]


In [84]:
# 4
'''
Insert the correct slicing syntax to print the following selection of the array:

Every other item from the entire array.

Tip: use the step syntax.


arr = np.array([10, 15, 20, 25, 30, 35, 40])

print(arr[?])
'''

arr = np.array([10, 15, 20, 25, 30, 35, 40])

print(arr[::2])

[10 20 30 40]


### Data Types

- i - integer
- b - boolean
- u - unsigned integer
- f - float
- c - complex float
- m - timedelta
- M - datetime
- O - object
- S - string
- U - unicode string
- V - fixed chunk of memory for other type ( void )

In [85]:
# Checking the Data Type of an Array

A = np.array([3,1,6,2])

A.dtype

dtype('int32')

In [86]:
B = np.array(['apple', 'orange', 'banana'])

B.dtype

dtype('<U6')

In [87]:
# defined data types
C = np.array(['apple', 'orange', 'banana'], dtype='S')

C.dtype

dtype('S6')

In [88]:
## data types 4 bytes integer

D = np.array([2, 1, 6, 9, 3, 10], dtype='i4')

D.dtype

dtype('int32')

In [89]:
E = np.array(['a', '1', '2', '3'], dtype='i')


ValueError: invalid literal for int() with base 10: 'a'

#### Converting Data Type on Existing Arrays


In [ ]:
F = np.array([3.1, 9.6, 1.5])

new_arr = F.astype('i')

print(F)
print(F.dtype)

print(new_arr)
print(new_arr.dtype)

In [ ]:
# alternative way to converting float to int
n = F.astype(int)
n.dtype

In [ ]:
b = np.array([1, 0, 3, 7, 2])

new = b.astype(bool)
print(new)
new.dtype

### Copy vs View

- Copy - The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.
- View - The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [ ]:
# Copy

ar = np.array([2,4,6,8])

print(ar)

# copy
cp = ar.copy()
print(cp)
# updating
cp[2] = 1
print(cp)

print(ar) # not affected

ar[1] = 3
print(ar)
print(cp)

In [ ]:
# View

vr = np.array([1,3,5,7,9])

print(vr)

# view
cpv = vr.view()
print(cpv)
cpv[3] = 4
print(cpv) # changing
print(vr) # affected

vr[1] = 8
print(cpv) # affected

### Shape of an Array

In [ ]:
# The shape of an array is the number of elements in each dimension.

## NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

# 2-D array
arr = np.array(
    [
        [1,2,3],
        [4,5,6]
    ]
)

arr.shape

In [ ]:
brr = np.array(
    [
        [2,4,6,8],
        [1,3,5,7],
        [1,2,3,4,]
    ]
)

brr.shape # expected output: (3, 4) where 3 = dimension and 4 is the number of elements in each dimension of the array, respectively.

In [ ]:
crr = np.array([1,2,3,4], ndmin=5)

print(crr)
crr.shape

In [ ]:
frr = np.array(
    [
        [
            [
                [
                    [1,2,3,4]
                ]
            ]
        ]
    ]
)
print(frr)
frr.shape

In [ ]:
drr = np.array(
    [
        [
            [1,3,4],
            [1,3,4],
            [3,5,9]
        ],
        [
            [1,3,4],
            [1,3,4],
            [3,5,9]
        ]
    ]
)

print(drr)
drr.shape

In [ ]:
########################################
# practice

A = np.array(
    [
        [1,5,9],
        [3,18,2],
        [4,7,0]
    ]
)

A.shape # (3,3)

In [ ]:
# practice

A=np.array(
    [
        [
            [2,4,6],
            [1,3,5],
            [0,-1,3]
        ]
    ]
)

A.shape

In [ ]:
# practice

A=np.array(
    [ [ [ [ [1,2,3] ] ] ] ]
)

A.shape

In [ ]:
# practice

A=np.array([3,6,1])
A.shape

In [ ]:
## exercise
############## Use the correct NumPy method to change the shape of an array from 1-D to 2-D.

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

print(arr.shape)
newarr = arr.reshape(4, 3) # with the helkp of reshape() method
newarr.shape

In [ ]:
# exercise
########### Use a correct NumPy method to change the shape of an array from 2-D to 1-D.

arr = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]])
print(arr.shape)

newarr = arr.reshape(-1)
print(newarr.shape)