In [15]:
import numpy as np

np.__version__

'1.25.2'

In [16]:
arr1 = np.arange(50) # 0 to 49
arr1, arr1.dtype

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]),
 dtype('int64'))

In [17]:
arr2 = np.random.randint(0, 50, 50)
arr2, arr2.dtype

(array([37, 22, 37, 38, 41, 35, 39,  1, 29, 11, 41,  9, 30, 34, 13, 23, 22,
        37,  9, 10, 11, 43, 28,  3,  0, 34, 39, 41, 16, 14, 32, 22,  9,  3,
         0, 48,  8, 10,  0, 49, 15, 27, 25, 30, 19, 16, 14, 23, 31, 12]),
 dtype('int64'))

In [18]:
len(arr2)

50

In [19]:
arr3 = np.random.rand(50)
arr3, arr3.dtype

(array([0.72153998, 0.98868093, 0.43785159, 0.05950565, 0.81205559,
        0.84891331, 0.49112825, 0.73687195, 0.37748197, 0.00462432,
        0.92900389, 0.81536589, 0.43411044, 0.53742046, 0.81156653,
        0.3147773 , 0.59762637, 0.84948754, 0.90063032, 0.17039542,
        0.20982231, 0.43597811, 0.38741962, 0.78631306, 0.57573501,
        0.49029311, 0.09340286, 0.52865929, 0.23538726, 0.31614302,
        0.0433329 , 0.06376722, 0.04753596, 0.55658837, 0.07110983,
        0.40565042, 0.45758302, 0.36211431, 0.91915268, 0.53049246,
        0.77644548, 0.58627511, 0.26355941, 0.1219032 , 0.1991548 ,
        0.18849197, 0.48142093, 0.23556868, 0.65812279, 0.14907104]),
 dtype('float64'))

In [24]:
new_array1 = arr1 + 10 * np.random.randn(50)
new_array1

array([14.58993118, -8.31697911, 28.37354699, -9.75872694, 10.1691992 ,
       11.4228697 , 11.50527493, -4.65754171, -1.57519095, 14.07301144,
        0.71062069, 32.13503994, -8.36394497,  5.15206956, 30.14188848,
       21.51715309,  7.30376072, 19.032855  , 27.35499766,  1.49803548,
       27.49552211, 41.07011473, 28.79961048, 33.67487594, 37.06011104,
       29.50228233, 24.77910183, 25.20853854, 24.74082434, 10.51085378,
       18.2847568 , 36.1192305 , 17.4261313 , 48.12228393, 28.48979559,
       41.45135775, 25.76641818, 33.90336378, 23.92106851, 38.57662958,
       24.05860024, 43.6061932 , 48.83332031, 40.5918478 , 47.41911571,
       49.79873238, 54.57941758, 67.48299564, 37.83291192, 45.46614905])

In [27]:
print(arr3)
new_array2 = np.abs(arr3 * 100)
new_array2

[0.72153998 0.98868093 0.43785159 0.05950565 0.81205559 0.84891331
 0.49112825 0.73687195 0.37748197 0.00462432 0.92900389 0.81536589
 0.43411044 0.53742046 0.81156653 0.3147773  0.59762637 0.84948754
 0.90063032 0.17039542 0.20982231 0.43597811 0.38741962 0.78631306
 0.57573501 0.49029311 0.09340286 0.52865929 0.23538726 0.31614302
 0.0433329  0.06376722 0.04753596 0.55658837 0.07110983 0.40565042
 0.45758302 0.36211431 0.91915268 0.53049246 0.77644548 0.58627511
 0.26355941 0.1219032  0.1991548  0.18849197 0.48142093 0.23556868
 0.65812279 0.14907104]


array([72.1539976 , 98.86809261, 43.78515919,  5.95056459, 81.20555915,
       84.89133098, 49.11282545, 73.68719487, 37.74819683,  0.46243194,
       92.90038861, 81.53658914, 43.41104385, 53.74204576, 81.15665314,
       31.47773043, 59.76263678, 84.9487544 , 90.06303195, 17.03954177,
       20.982231  , 43.59781054, 38.74196194, 78.63130559, 57.57350114,
       49.02931061,  9.34028635, 52.86592883, 23.53872601, 31.61430236,
        4.33328963,  6.37672241,  4.75359557, 55.65883714,  7.11098261,
       40.56504217, 45.758302  , 36.21143132, 91.91526794, 53.04924566,
       77.64454787, 58.62751115, 26.35594146, 12.1903195 , 19.91548022,
       18.84919713, 48.14209343, 23.55686808, 65.81227927, 14.90710415])